kind: Service
apiVersion: v1
metadata:
  name: maker-bot
  labels:
    app: maker-bot
spec:
  selector:
    app: maker-bot
  ports:
    - port: 9080
      name: http
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: maker-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maker-bot
        version: v1
    spec:
      containers:
      - name: maker-bot
        image: docker.sebastian-daschner.com/maker-bot:1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/
          initialDelaySeconds: 40
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -f localhost:9080/maker-bot/resources/health
          initialDelaySeconds: 60
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
#kind: Ingress
#apiVersion: extensions/v1beta1
#metadata:
#  name: maker-bot
#  annotations:
#    kubernetes.io/ingress.class: istio
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /maker-bot/.*
#        backend:
#          serviceName: maker-bot
#          servicePort: 9080
#---